language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
- pip install tpDcc-libs-unittests
- pip install tpDcc-dccs-standalone
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --exclude */externals/* --max-line-length=120
  --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: ObWQabBnxVcd8IXH/KiJrk5VQb+4T3CU3vlWWgF3s5eqVtzb2Vn6XYheX6kq4KKvHll4svcCgbXrzMgPXFzNhUzmifoMuQ/l8+TIcAvFpE6B3Rj2NW1yO18h1bmkekgkBmq0f4Ea4HjhKGFxBUlJjwzWjlKT7imMYBFNbcJ8i8AisfAPbZIg/eduYKOngF4lRylQ96ucvZc+PLuq+UgB2WxL1DuIgGyxa5h9MOx3iGjVQIYJOiOXC0UgjM2KnJd3+LHyUVDa2yfZtvJgaSIFxGyCP/G6lSwSK23NmOakdb6gBZh+xZyt1i81GMtTkkP9Zs2+VwDFsObi9N2SFzNCym3fMAAMJgIVkI8HYJC6J0PFHyMRjT4oHznEZc+dn2bNHx6srq9eUyTwCSb8F05011iHTZmgBqAP3Cpg9LliP8OoRrB/fUDtBexz5yrdbGpqCDARomcBF1TOIhHDNE2Jj6rd3gO8Wah1A3DiPSZI2cGqdFwXijyFSLqIpz6DSWQ3eZ1/UsWmFeYVaJDVIwWyjLZkvF8JPedXHDrZwII/giM1HCkkTXZ68wasqyQUURbjRs9g5mB8OBYewaol4uagMg5hkq3TArtoBd8mnaTR/1uy4NrFEIgoHf6ys7eGhNVgDk21UWPp0Bge9/5fNSJmRiOLO7Ru6muiYsiPJCwRL14=
    on:
      branch: master
      tags: true